# Generated by Django 6.1.1 on 2026-09-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Selling_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitems',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
    ]
