# Generated by Django 6.1.1 on 2026-09-15 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Selling_system', '0002_saleitems_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitems',
            name='price_at_sale',
        ),
        migrations.RemoveField(
            model_name='saleitems',
            name='total_price',
        ),
    ]
