# Generated by Django 6.1.1 on 2026-09-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Selling_system', '0003_remove_saleitems_price_at_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitems',
            name='price_at_sale',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitems',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
