# Generated by Django 6.1.1 on 2026-09-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Selling_system', '0004_saleitems_price_at_sale_saleitems_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitems',
            name='price_at_sale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleitems',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
