# Generated by Django 6.1.1 on 2026-09-15 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Selling_system', '0005_alter_saleitems_price_at_sale_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitems',
            name='price_at_sale',
        ),
        migrations.RemoveField(
            model_name='saleitems',
            name='total_price',
        ),
    ]
