# Generated by Django 6.1.1 on 2026-09-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Selling_system', '0007_saleitems_price_at_sale_saleitems_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
