# Generated by Django 6.1.1 on 2026-09-20 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Selling_system', '0008_sales_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitems',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saleitems', to='Selling_system.products'),
        ),
    ]
